services:
  postgres:
    container_name: goodreads-postgres
    image: postgres:13.16
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  backend:
    container_name: goodreads-backend
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres:
